config/routes.rb
IAmTheLider::Application.routes.draw do
  root to: 'welcome#index'

  mount Ckeditor::Engine => '/ckeditor'

  resources :news, only: [ :show, :index ]
  resources :stages, only: [] do
    member do
      resources :ratings, only: :index
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :blog_posts, only: [ :index, :show ]
  resources :users do
    member do
      resource :works, except: [ :index, :show ]
    end
  end
  resource :welcome, only: :index do
    collection do
      get "first_stage" => "welcome#first_stage"
      get "second_stage" => "welcome#second_stage"
      get "third_stage" => "welcome#third_stage"
      get "competition" => "welcome#competition"
      get "reg_end" => "welcome#reg_end"
    end
  end
  resources :events, only: [ :index, :show ]
  resource :errors, only: [] do
    collection do
      get "not_found"
    end
  end
  namespace :participant do
    resources :users do
      member do
        resources :welcome, only: :index
        resources :blog_posts
        resource :event do
          scope module: :event do
            resource :report, except: :show do
              member do
                resources :participants, except: [ :show, :index ]
                resources :photos, except: [ :show, :index, :edit, :update ]
              end
            end
          end
        end
      end
    end
  end
  namespace :admin do
    resource :session, only: [ :new, :create, :destroy ]
    resources :welcome, only: [ :index ]
    resources :blog_posts, except: [:create, :new]
    resources :news, except: [ :index, :show ]
    resources :events
    resources :reports
    resources :participants, except: [ :show, :edit, :update ]
    resources :users do
      member do
        put :accept
        put :reserve
        put :update_stage
        resource :reserve_reason, except: [ :index, :show ]
      end
    end
    resources :jurors, except: [:show, :new, :index]
    resources :stages do
      member do
        put :publish
        put :unpublish
        resources :criterions, except: :show
        resources :jurors, only: [:new, :index]
        resources :ratings, only: :index
      end
    end
  end
  get "admin" => "admin/welcome#index"
  namespace :juror do
    resource :session, only: [ :new, :create, :destroy ]
    resources :welcome, only: :index
    resources :users, only: :index do
      member do
        resources :ratings, only: :new
      end
    end
    resources :ratings, only: [:create, :edit, :update]
  end
  get "juror" => "juror/welcome#index"
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :juror_id, :user_id, :evaluations_attributes

  include UsefullScopes

  belongs_to :user
  belongs_to :juror
  has_many :evaluations
  accepts_nested_attributes_for :evaluations

  validates :juror_id, presence: true
  validates :user_id, presence: true
end

app/controllers/admin/ratings_controller.rb
class Admin::RatingsController < Admin::ApplicationController
  def index
    @users = UserDecorator.decorate_collection User.where("last_stage_id >= ?", params[:id])
    @stage = Stage.find params[:id]
  end
end

app/controllers/juror/ratings_controller.rb
class Juror::RatingsController < ApplicationController
  def new
    @user = User.find(params[:id]).decorate
    @criterions = current_juror.stage.criterions
    @rating = Rating.new
    @rating.evaluations.build
  end

  def create
    @rating = Rating.new params[:rating]
    if @rating.save
      redirect_to juror_users_path, flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def edit
    @rating = Rating.find params[:id]
    @user = User.find(params[:id]).decorate
    @criterions = current_juror.stage.criterions
  end

  def update
    @rating = Rating.find params[:id]
    if @rating.update_attributes params[:rating]
      redirect_to juror_users_path, flash: :success
    else
      render action: :edit, flash: :error
    end
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
    @stage = Stage.find params[:id]
    if @stage.published?
      @users = UserDecorator.decorate_collection User.where("last_stage_id >= ?", params[:id])
    else
      redirect_to not_found_errors_path
    end
  end
end

app/helpers/juror/ratings_helper.rb
module Juror::RatingsHelper
  def user_has_rating?(user, juror)
    user.ratings & juror.ratings
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/admin/ratings/index.html.haml
= stylesheet_link_tag "users"
.page-header
  %h1
    = t('.title')
  - unless @stage.average
    = link_to t('.add_stage_average'), edit_admin_stage_path(@stage), class: 'btn btn-info'
  - if @stage.not_published?
    = link_to t('.publish_ratings'), publish_admin_stage_path(@stage), method: :put, class: 'btn btn-success'
  - else
    = link_to t('.unpublish_ratings'), unpublish_admin_stage_path(@stage), method: :put, class: 'btn btn-success'
- @users.each do |user|
  .row-fluid.has_top_margin
    .span2
      %img.img-polaroid{ src: user.avatar.thumb_fill }
    .span3
      .row-fluid
        %h4
          - if admin_signed_in?
            = user.title
          - else
            = user.small_name
      .row-fluid
        %h4= user.district.title
    .span3
      - if user.has_ratings_on_stage?(@stage)
        %h4
          %table.table.table-striped.table-bordered
            - user.ratings_on_stage(@stage).each do |rating|
              %tr
                %td
                  = rating.juror.decorate.full_name
                  -
                  = rating.decorate.sum
            %tr
              %td
                = t('.average_eval')
                = user.average_eval(@stage)
    .span3
      = user.has_entered?(@stage)