config/routes.rb
IAmTheLider::Application.routes.draw do
  root to: 'welcome#index'

  mount Ckeditor::Engine => '/ckeditor'

  resources :news, only: [ :show, :index ]
  resources :stages, only: [] do
    member do
      resources :ratings, only: :index
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :blog_posts, only: [ :index, :show ]
  resources :users do
    member do
      resource :works, except: [ :index, :show ]
    end
  end
  resource :welcome, only: :index do
    collection do
      get "first_stage" => "welcome#first_stage"
      get "second_stage" => "welcome#second_stage"
      get "third_stage" => "welcome#third_stage"
      get "competition" => "welcome#competition"
      get "reg_end" => "welcome#reg_end"
    end
  end
  resources :events, only: [ :index, :show ]
  resource :errors, only: [] do
    collection do
      get "not_found"
    end
  end
  namespace :participant do
    resources :users do
      member do
        resources :welcome, only: :index
        resources :blog_posts
        resource :event do
          scope module: :event do
            resource :report, except: :show do
              member do
                resources :participants, except: [ :show, :index ]
                resources :photos, except: [ :show, :index, :edit, :update ]
              end
            end
          end
        end
      end
    end
  end
  namespace :admin do
    resource :session, only: [ :new, :create, :destroy ]
    resources :welcome, only: [ :index ]
    resources :blog_posts, except: [:create, :new]
    resources :news, except: [ :index, :show ]
    resources :events
    resources :reports
    resources :participants, except: [ :show, :edit, :update ]
    resources :users do
      member do
        put :accept
        put :reserve
        put :update_stage
        resource :reserve_reason, except: [ :index, :show ]
      end
    end
    resources :jurors, except: [:show, :new, :index]
    resources :stages do
      member do
        put :publish
        put :unpublish
        resources :criterions, except: :show
        resources :jurors, only: [:new, :index]
        resources :ratings, only: :index
      end
    end
  end
  get "admin" => "admin/welcome#index"
  namespace :juror do
    resource :session, only: [ :new, :create, :destroy ]
    resources :welcome, only: :index
    resources :users, only: :index do
      member do
        resources :ratings, only: :new
      end
    end
    resources :ratings, only: [:create, :edit, :update]
  end
  get "juror" => "juror/welcome#index"
end

app/models/event.rb
class Event < ActiveRecord::Base
  geocoded_by :adress
  #after_validation :geocode, if: :adress_changed?

  attr_accessible :adress,
                  :begin_date,
                  :description,
                  :end_date,
                  :goal,
                  :participant_category,
                  :tasks,
                  :title,
                  :user_id,
                  :latitude,
                  :longtitude

  belongs_to :user
  has_one :report

  validates :adress, presence: true
  validates :begin_date, presence: true
  validates :end_date, presence: true
  validates :description, presence: true,
                          length: { maximum: 1000 }
  validates :goal, presence: true
  validates :participant_category, presence: true
  validates :tasks, presence: true
  validates :title, presence: true,
                    length: { maximum: 140 }
  validates :user_id, presence: true

  #FIXME for simple calendar gem
  def start_time
    begin_date
  end
end

app/models/event/participant.rb
class Event::Participant < ActiveRecord::Base
  attr_accessible :report_id,
                  :full_name,
                  :group,
                  :phone,
                  :school

  belongs_to :report

  validates :report_id, presence: true
  validates :full_name, presence: true
  validates :phone, phone: true, allow_blank: true
end

app/models/event/photo.rb
class Event::Photo < ActiveRecord::Base
  attr_accessible :file, :report_id

  belongs_to :report

  mount_uploader :file, PhotoUploader

  validates :file, presence: true
  validates :report_id, presence: true
end

app/models/event/report.rb
class Event::Report < ActiveRecord::Base
  attr_accessible :description, :document, :event_id, :results, :participants_attributes

  belongs_to :event
  has_many :participants, class_name: "Event::Participant"

  mount_uploader :document, DocumentUploader

  validates :description, presence: true
  validates :results, presence: true
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::ApplicationController
  def show
    @event = Event.find(params[:id]).decorate
  end

  def index
    @events = Event.all
  end

  def new
    if not current_stage or (current_stage and User.with(last_stage_id: current_stage.id).select { |user| user.event.nil? }.any?)
      @event = Event.new
    else
      redirect_to new_admin_user_path, flash: :error
    end
  end

  def edit
    @event = Event.find_by_user_id params[:id]
  end

  def create
    @event = Event.new params[:event]
    if @event.save
      redirect_to admin_event_path(@event), flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def update
    @event = Event.find params[:id]
    if @event.update_attributes params[:event]
      redirect_to admin_event_path(@event), flash: :success
    else
      render action: :edit, flash: :error
    end
  end

  def destroy
    @event = Event.find params[:id]
    user = @event.user
    @event.destroy
    redirect_to admin_welcome_index_path, flash: :success
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.order("begin_date")
  end

  def show
    @event = Event.find(params[:id]).decorate
  end
end

app/controllers/participant/event/application_controller.rb
class Participant::Event::ApplicationController < Participant::ApplicationController
end

app/controllers/participant/event/participants_controller.rb
class Participant::Event::ParticipantsController < Participant::Event::ApplicationController
  def new
    @participant = Event::Participant.new
  end

  def edit
    @participant = Event::Participant.find params[:id]
  end

  def create
    @participant = Event::Participant.new params[:event_participant]
    if @participant.save
      redirect_to participant_event_path(@participant), flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def update
    @participant = Event::Participant.find params[:id]
    if @participant.update_attributes params[:event_participant]
      redirect_to participant_event_path(@participant), flash: :success
    else
      render action: :edit, flash: :error
    end
  end

  def destroy
    @participant = Event::Participant.find params[:id]
    event = @participant.report.event
    @participant.destroy
    redirect_to participant_event_path(event), flash: :success
  end
end

app/controllers/participant/event/photos_controller.rb
class Participant::Event::PhotosController < Participant::Event::ApplicationController
  def new
    @photo = Event::Photo.new
  end

  def create
    @photo = Event::Photo.new params[:event_photo]
    if @photo.save
      redirect_to participant_event_path(@photo), flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def destroy
    @photo = Event::Photo.find params[:id]
    event = @photo.report.event
    @photo.destroy
    redirect_to participant_event_path(event), flash: :success
  end
end

app/controllers/participant/event/reports_controller.rb
class Participant::Event::ReportsController < Participant::Event::ApplicationController
  def new
    @report = Event::Report.new
    @report.participants.build
  end

  def edit
    @report = Event::Report.find_by_event_id (Event.find_by_user_id params[:id]).id
  end

  def create
    @report = Event::Report.new params[:event_report]
    if @report.save
      redirect_to participant_event_path(@report.event.user), flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def update
    @report = Event::Report.find params[:id]
    if @report.update_attributes params[:event_report]
      redirect_to "/participant/users/#{@report.event.user}/event", flash: :success
    else
      render action: :edit, flash: :error
    end
  end

  def destroy
    @report = Event::Report.find params[:id]
    user = @report.event.user
    @report.destroy
    redirect_to participant_welcome_index_path(user), flash: :success
  end

end

app/controllers/participant/events_controller.rb
class Participant::EventsController < Participant::ApplicationController
  def show
    @event = Event.find_by_user_id(params[:id]).decorate
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find params[:id]
  end

  def create
    @event = Event.new params[:event]
    if @event.save
      redirect_to participant_event_path(@event), flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def update
    @event = Event.find params[:id]
    if @event.update_attributes params[:event]
      redirect_to participant_event_path(@event.user), flash: :success
    else
      render action: :edit, flash: :error
    end
  end

  def destroy
    @event = Event.find params[:id]
    user = @event.user
    @event.destroy
    redirect_to participant_welcome_index_path(user), flash: :success
  end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
  def users_without_events
    if current_stage
      User.with(last_stage_id: current_stage.id).select { |user| user.event.nil? }
    else
      User.all
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def participants_count(count)
    "#{count} #{Russian.p(count, I18n.t('participants.participant'), I18n.t('participants.few_participants'), I18n.t('participants.many_participants'))}"
  end
end

app/helpers/participant/event/application_helper.rb
module Participant::Event::ApplicationHelper
end

app/helpers/participant/event/participants_helper.rb
module Participant::Event::ParticipantsHelper
end

app/helpers/participant/event/photos_helper.rb
module Participant::Event::PhotosHelper
end

app/helpers/participant/event/report_helper.rb
module Participant::Event::ReportHelper
end

app/helpers/participant/events_helper.rb
module Participant::EventsHelper
end

app/views/admin/events/_form.html.haml
= javascript_include_tag "http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=true&language=ru"
= javascript_include_tag "participant/geo_marker"
= stylesheet_link_tag "participant/events"

= simple_form_for @event, url: "/admin/events/#{@event.id}", html: { class: 'form-horizontal' } do |f|
  - f.with_options input_html: { class: :span6 } do |f|
    = f.input :title, as: :string
    = f.input :goal, as: :string
    = f.input :tasks
    = f.input :participant_category
    = f.input :description
    = f.input :begin_date, input_html: { class: :span1 }
    = f.input :end_date, input_html: { class: :span1 }
    = f.association :user, label_method: lambda { |user| "#{user.first_name} #{user.middle_name}" }, value_method: :id, collection: users_without_events
    = f.input :adress, as: :string
  .form-actions
    = f.button :submit, t('save'), class: 'btn btn-primary'

app/views/admin/events/edit.html.haml
- model_class = Event
.page-header
  %h1=t '.title'
= render partial: "form"

app/views/admin/events/index.html.haml
= stylesheet_link_tag "events"
= stylesheet_link_tag "admin/events"

.page-header
  %h1= t('.title')
= link_to t('helpers.links.new'), new_admin_event_path, class: 'btn btn-primary'
- if @events.any?
  - @events.each do |event|
    .well.link{ onclick: "return location.href = '#{admin_event_path(event)}'" }
      .row-fluid
        .span10
          = image_tag event.user.avatar.thumb
          %small
            = event.user.decorate.small_name
            |
            =l event.begin_date.to_date
            |
            = event.adress
          %h4= event.title
          %p
            != strip_tags event.description.first(250)
            %b ...
        .span2
          - if event.report.present?
            .well.green
              = t('.report_is_present')
          - else
            .well.red
              = t('.report_is_not_present')
- else
  = t('.no_events')

app/views/admin/events/new.html.haml
- model_class = Event
.page-header
  %h1=t '.title', default: [:'helpers.titles.new', 'Новое %{model}'], model: model_class.model_name.human.titleize
= render partial: "form"

app/views/admin/events/show.html.haml
= stylesheet_link_tag "participant/events"
%script{src: "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry", type: "text/javascript"}
%script{src: "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", type: "text/javascript"}
= javascript_include_tag "participant/events"
- model_class = Event
.page-header
  %h1
    = @event.title
.row-fluid
  .span6
    .row-fluid
      %p
        %strong= model_class.human_attribute_name(:goal) + ':'
        %br
        = @event.goal
      %p
        %strong= model_class.human_attribute_name(:tasks) + ':'
        %br
        = @event.tasks
      %p
        %strong= model_class.human_attribute_name(:participant_category) + ':'
        %br
        = @event.participant_category
      %p
        %strong= model_class.human_attribute_name(:description) + ':'
        %br
        = @event.description
      %p
        %strong= model_class.human_attribute_name(:begin_date) + ':'
        %br
        =l @event.begin_date
      %p
        %strong= model_class.human_attribute_name(:end_date) + ':'
        %br
        =l @event.end_date
      %p
        %strong= model_class.human_attribute_name(:adress) + ':'
        %br
        = @event.adress
    .row-fluid
      .form-actions
        = link_to t('edit', default: t("helpers.links.edit")), edit_admin_event_path(@event), class: 'btn'
        = link_to t('destroy', default: t("helpers.links.destroy")), admin_event_path(@event), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'
    - if @event.report.present?
      .row-fluid
        %h2
          Творческий отчёт о мероприятии
        %p
          %strong= model_class.human_attribute_name(:description) + ':'
          %br
          != @event.report.description
          %strong= model_class.human_attribute_name(:results) + ':'
          %br
          = @event.report.results

        %p
          .form-actions
            = link_to t('edit', default: t("helpers.links.edit")), edit_admin_report_path(@event.report), class: 'btn'
            = link_to t('destroy', default: t("helpers.links.destroy")), admin_report_path(@event.report), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'
    - else
      = link_to t('.add_report'), new_admin_report_path, class: 'btn btn-primary'
  .span6
    .row
      .button{ onclick: "return location.href = '#{admin_user_path(@event.user)}'" }
        = image_tag @event.user.avatar.mini_thumb_fill
        = @event.user.decorate.small_name
      - if @event.user.twitter?
        .button{ onclick: "return location.href = '#{@event.user.twitter}'" }
          = image_tag "social/twitter.png"
          = @event.user.decorate.twitter_account
    -#.row
      %div{style: "width: 800px;"}
        #google_map{style: "width: 800px; height: 400px;"}
    - if @event.report.present?
      %hr
      .row-fluid
        %h3= t('.participants')
        = link_to t('new'), new_admin_participant_path, class: 'btn btn-success'
        %table.table.table-striped
          - @event.report.participants.each do |participant|
            %tr
              %td
                = participant.full_name
              %td
                = participant.phone
              %td
                = participant.school
              %td
                = participant.group
              %td
                = link_to t('destroy'), admin_participant_path(participant), method: :delete, class: 'btn btn-mini btn-danger'