config/routes.rb
IAmTheLider::Application.routes.draw do
  root to: 'welcome#index'

  mount Ckeditor::Engine => '/ckeditor'

  resources :news, only: [ :show, :index ]
  resources :stages, only: [] do
    member do
      resources :ratings, only: :index
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :blog_posts, only: [ :index, :show ]
  resources :users do
    member do
      resource :works, except: [ :index, :show ]
    end
  end
  resource :welcome, only: :index do
    collection do
      get "first_stage" => "welcome#first_stage"
      get "second_stage" => "welcome#second_stage"
      get "third_stage" => "welcome#third_stage"
      get "competition" => "welcome#competition"
      get "reg_end" => "welcome#reg_end"
    end
  end
  resources :events, only: [ :index, :show ]
  resource :errors, only: [] do
    collection do
      get "not_found"
    end
  end
  namespace :participant do
    resources :users do
      member do
        resources :welcome, only: :index
        resources :blog_posts
        resource :event do
          scope module: :event do
            resource :report, except: :show do
              member do
                resources :participants, except: [ :show, :index ]
                resources :photos, except: [ :show, :index, :edit, :update ]
              end
            end
          end
        end
      end
    end
  end
  namespace :admin do
    resource :session, only: [ :new, :create, :destroy ]
    resources :welcome, only: [ :index ]
    resources :blog_posts, except: [:create, :new]
    resources :news, except: [ :index, :show ]
    resources :events
    resources :reports
    resources :participants, except: [ :show, :edit, :update ]
    resources :users do
      member do
        put :accept
        put :reserve
        put :update_stage
        resource :reserve_reason, except: [ :index, :show ]
      end
    end
    resources :jurors, except: [:show, :new, :index]
    resources :stages do
      member do
        put :publish
        put :unpublish
        resources :criterions, except: :show
        resources :jurors, only: [:new, :index]
        resources :ratings, only: :index
      end
    end
  end
  get "admin" => "admin/welcome#index"
  namespace :juror do
    resource :session, only: [ :new, :create, :destroy ]
    resources :welcome, only: :index
    resources :users, only: :index do
      member do
        resources :ratings, only: :new
      end
    end
    resources :ratings, only: [:create, :edit, :update]
  end
  get "juror" => "juror/welcome#index"
end

app/models/event/participant.rb
class Event::Participant < ActiveRecord::Base
  attr_accessible :report_id,
                  :full_name,
                  :group,
                  :phone,
                  :school

  belongs_to :report

  validates :report_id, presence: true
  validates :full_name, presence: true
  validates :phone, phone: true, allow_blank: true
end

app/controllers/admin/participants_controller.rb
class Admin::ParticipantsController < Admin::ApplicationController
  def index
    @participants = Event::Participant.all
  end

  def new
    @participant = Event::Participant.new
  end

  def create
    @participant = Event::Participant.new params[:event_participant]
    if @participant.save
      redirect_to admin_event_path(@participant.report.event), flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def destroy
    @participant = Event::Participant.find params[:id]
    event = @participant.report.event
    @participant.destroy
    redirect_to admin_event_path(event), flash: :success
  end
end

app/controllers/admin/welcome_controller.rb
class Admin::WelcomeController < Admin::ApplicationController
  def index
    @events = Event.all
  end
end

app/controllers/juror/welcome_controller.rb
class Juror::WelcomeController < Juror::ApplicationController
  def index
  end
end

app/controllers/participant/application_controller.rb
class Participant::ApplicationController < ApplicationController
  before_filter :check_user_signed
end

app/controllers/participant/blog_posts_controller.rb
class Participant::BlogPostsController < Participant::ApplicationController
  def index
    @blog_posts = BlogPostDecorator.decorate_collection User.find(params[:id]).blog_posts.reverse
  end

  def show
    @blog_post = BlogPost.find params[:id]
  end

  def new
    @blog_post = BlogPost.new
    @blog_post.user_id = current_user.id
  end

  def edit
    @blog_post = BlogPost.find params[:id]
  end

  def create
    @blog_post = BlogPost.new params[:blog_post]
    if @blog_post.save
      redirect_to participant_blog_posts_path(@blog_post.user), flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def update
    @blog_post = BlogPost.find params[:id]
    if @blog_post.update_attributes params[:blog_post]
      redirect_to participant_blog_post_path(@blog_post), flash: :success
    else
      render action: :edit, flash: :error
    end
  end

  def destroy
    @blog_post = BlogPost.find params[:id]
    user = @blog_post.user
    @blog_post.destroy
    redirect_to participant_blog_posts_path(user), flash: :success
  end
end

app/controllers/participant/event/application_controller.rb
class Participant::Event::ApplicationController < Participant::ApplicationController
end

app/controllers/participant/event/participants_controller.rb
class Participant::Event::ParticipantsController < Participant::Event::ApplicationController
  def new
    @participant = Event::Participant.new
  end

  def edit
    @participant = Event::Participant.find params[:id]
  end

  def create
    @participant = Event::Participant.new params[:event_participant]
    if @participant.save
      redirect_to participant_event_path(@participant), flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def update
    @participant = Event::Participant.find params[:id]
    if @participant.update_attributes params[:event_participant]
      redirect_to participant_event_path(@participant), flash: :success
    else
      render action: :edit, flash: :error
    end
  end

  def destroy
    @participant = Event::Participant.find params[:id]
    event = @participant.report.event
    @participant.destroy
    redirect_to participant_event_path(event), flash: :success
  end
end

app/controllers/participant/event/photos_controller.rb
class Participant::Event::PhotosController < Participant::Event::ApplicationController
  def new
    @photo = Event::Photo.new
  end

  def create
    @photo = Event::Photo.new params[:event_photo]
    if @photo.save
      redirect_to participant_event_path(@photo), flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def destroy
    @photo = Event::Photo.find params[:id]
    event = @photo.report.event
    @photo.destroy
    redirect_to participant_event_path(event), flash: :success
  end
end

app/controllers/participant/event/reports_controller.rb
class Participant::Event::ReportsController < Participant::Event::ApplicationController
  def new
    @report = Event::Report.new
    @report.participants.build
  end

  def edit
    @report = Event::Report.find_by_event_id (Event.find_by_user_id params[:id]).id
  end

  def create
    @report = Event::Report.new params[:event_report]
    if @report.save
      redirect_to participant_event_path(@report.event.user), flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def update
    @report = Event::Report.find params[:id]
    if @report.update_attributes params[:event_report]
      redirect_to "/participant/users/#{@report.event.user}/event", flash: :success
    else
      render action: :edit, flash: :error
    end
  end

  def destroy
    @report = Event::Report.find params[:id]
    user = @report.event.user
    @report.destroy
    redirect_to participant_welcome_index_path(user), flash: :success
  end

end

app/controllers/participant/events_controller.rb
class Participant::EventsController < Participant::ApplicationController
  def show
    @event = Event.find_by_user_id(params[:id]).decorate
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find params[:id]
  end

  def create
    @event = Event.new params[:event]
    if @event.save
      redirect_to participant_event_path(@event), flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def update
    @event = Event.find params[:id]
    if @event.update_attributes params[:event]
      redirect_to participant_event_path(@event.user), flash: :success
    else
      render action: :edit, flash: :error
    end
  end

  def destroy
    @event = Event.find params[:id]
    user = @event.user
    @event.destroy
    redirect_to participant_welcome_index_path(user), flash: :success
  end

end

app/controllers/participant/welcome_controller.rb
class Participant::WelcomeController < Participant::ApplicationController
  def index
    @blogs = User.find(params[:id]).blog_posts.reverse.last 3
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    current_users = User.with last_stage_id: current_stage.id
    @users = current_users.shuffle!.first 12
    @news = News.last(6).reverse
    @blogs = BlogPost.last(4).reverse
    @users_count = current_users.count
  end

  def first_stage
  end

  def second_stage
  end

  def third_stage
  end

  def competition
  end

  def reg_end
    if can_registred?
      redirect_to new_user_path
    end
  end
end

app/helpers/admin/participants_helper.rb
module Admin::ParticipantsHelper
end

app/helpers/juror/welcome_helper.rb
module Juror::WelcomeHelper
  def current_juror_decorate
    if current_juror
      current_juror.decorate
    end
  end
end

app/helpers/participant/event/application_helper.rb
module Participant::Event::ApplicationHelper
end

app/helpers/participant/event/participants_helper.rb
module Participant::Event::ParticipantsHelper
end

app/helpers/participant/event/photos_helper.rb
module Participant::Event::PhotosHelper
end

app/helpers/participant/event/report_helper.rb
module Participant::Event::ReportHelper
end

app/helpers/participant/events_helper.rb
module Participant::EventsHelper
end

app/views/participant/welcome/_blogs.html.haml
.well
  %h3
    = link_to participant_blog_posts_path(current_user) do
      = t('.my_blogs')
    = link_to t('.add_blog'), new_participant_blog_post_path(current_user), class: 'btn btn-primary'
  - @blogs.each do |blog|
    .well.link{ onclick: "return location.href = '#{participant_blog_post_path(blog)}'" }
      %a{ href: participant_blog_post_path(blog) }
        = image_tag blog.user.avatar.thumb
      %h4= blog.title
      %p
        != strip_tags blog.text.first(200)
        %b ...
      %small=l blog.created_at
  %br

app/views/participant/welcome/_you_are_loser.html.haml
%h2
  К сожалению, вы не смогли пройти в полуфинал конкурса "Я-лидер!". Не отчаивайтесь!! Ибо не ошибается тот, кто ничего не делает. Вы можете принять участие в следующем году.

app/views/participant/welcome/index.html.haml
= stylesheet_link_tag "participant/welcome"
- if participant_is_semifinalist?(current_user)
  .row-fluid
    .span6.main_text
      %h2
        Привет, полуфиналист конкурса
        %br
        "Я-лидер!"
      %p
        Ещё раз поздравляем тебя с победой на "Ярмарке идей" и напомнаем, что в рамках 2 уровня II этапа XII конкурса актива учащейся молодёжи "Я-лидер!" тебе необходимо вместе с командой единомышленников применить на практике полученные ранее знания, придумать, организовать и провести социально значимое мероприятие.
      %p
        %b ВНИМАНИЕ!
        Подготовку мероприятия следует подробно описывать в Дневнике участника. Это один из двух обязательных документов, которые должны быть у каждого полуфиналиста.
      %p
        Согласно п.5.2.2. Положения, все участники обязаны за неделю до начала мероприятия сообщить о дате его проведения в МИЦ.
      %p
        %b ВНИМАНИЕ!
        Чтобы сообщить нам о своём мероприятии тебе необходимо заполнить на этом сайте форму "Анонс мероприятия".
      %p
        По итогам проведённого мероприятия участникам необходимо представить в МИЦ творческий отчёт.
      %p
        %b Внимание!
        Отчёт предстоит также заполнить на данном сайте прикрепив к нему как можно больше материалов (фото, видео, отзывы и т.п.). Последний день заполнения творческого отчёта - 15 апреля 2014 года.
      %p
        .row-fluid
          .span5
            %span
              Вы, также, можете скачать расширение для Google Chrome для быстрого доступа к сайту конкурса
              = link_to configus.apps.chrome_web_store_url, target: "_blank" do
                = t('.here')
          .offset1.span6
            = link_to configus.apps.chrome_web_store_url, target: "_blank"  do
              = image_tag "app_markets/chrome_web_store.png"
      %p
        Если будут вопросы, всегда готовы на них ответить.
      %p
        %h3
          Желаем удачи!
      %p
        - unless current_user.event.present?
          = link_to t('.create_event'), new_participant_event_path(current_user), class: 'btn btn-success btn-large'
        - else
          = t('.here_you_can_add_participants_to_your_report')
          = link_to t('.view_my_event'), participant_event_path(current_user.event.user), class: 'btn btn-large'
          - if current_user.event.decorate.can_edit?
            = link_to t('.edit_event'), edit_participant_event_path(current_user.event), class: 'btn btn-warning btn-large'
          - else
            - unless user_event_happened?
              %p
                = t('.you_can_not_edit_event')
      %p
        - if user_event_happened?
          - unless current_user.event.report.present?
            = link_to t('.create_report'), new_participant_event_report_path(current_user.event), class: 'btn btn-success btn-large'
          - else
            = link_to t('.edit_report'), edit_participant_event_report_path(current_user), class: 'btn btn-wraning btn-large'
    .span5
      = render "blogs"
- else
  = render "you_are_loser"