config/routes.rb
IAmTheLider::Application.routes.draw do
  root to: 'welcome#index'

  mount Ckeditor::Engine => '/ckeditor'

  resources :news, only: [ :show, :index ]
  resources :stages, only: [] do
    member do
      resources :ratings, only: :index
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :blog_posts, only: [ :index, :show ]
  resources :users do
    member do
      resource :works, except: [ :index, :show ]
    end
  end
  resource :welcome, only: :index do
    collection do
      get "first_stage" => "welcome#first_stage"
      get "second_stage" => "welcome#second_stage"
      get "third_stage" => "welcome#third_stage"
      get "competition" => "welcome#competition"
      get "reg_end" => "welcome#reg_end"
    end
  end
  resources :events, only: [ :index, :show ]
  resource :errors, only: [] do
    collection do
      get "not_found"
    end
  end
  namespace :participant do
    resources :users do
      member do
        resources :welcome, only: :index
        resources :blog_posts
        resource :event do
          scope module: :event do
            resource :report, except: :show do
              member do
                resources :participants, except: [ :show, :index ]
                resources :photos, except: [ :show, :index, :edit, :update ]
              end
            end
          end
        end
      end
    end
  end
  namespace :admin do
    resource :session, only: [ :new, :create, :destroy ]
    resources :welcome, only: [ :index ]
    resources :blog_posts, except: [:create, :new]
    resources :news, except: [ :index, :show ]
    resources :events
    resources :reports
    resources :participants, except: [ :show, :edit, :update ]
    resources :users do
      member do
        put :accept
        put :reserve
        put :update_stage
        resource :reserve_reason, except: [ :index, :show ]
      end
    end
    resources :jurors, except: [:show, :new, :index]
    resources :stages do
      member do
        put :publish
        put :unpublish
        resources :criterions, except: :show
        resources :jurors, only: [:new, :index]
        resources :ratings, only: :index
      end
    end
  end
  get "admin" => "admin/welcome#index"
  namespace :juror do
    resource :session, only: [ :new, :create, :destroy ]
    resources :welcome, only: :index
    resources :users, only: :index do
      member do
        resources :ratings, only: :new
      end
    end
    resources :ratings, only: [:create, :edit, :update]
  end
  get "juror" => "juror/welcome#index"
end

app/models/event/report.rb
class Event::Report < ActiveRecord::Base
  attr_accessible :description, :document, :event_id, :results, :participants_attributes

  belongs_to :event
  has_many :participants, class_name: "Event::Participant"

  mount_uploader :document, DocumentUploader

  validates :description, presence: true
  validates :results, presence: true
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::ApplicationController
  def index
    @reports = Event::ReportDecorator.decorate_collection Event::Report.all
  end

  def new
    if Event.all.select { |event| event.report.nil? }.any?
      @report = Event::Report.new
    else
      redirect_to new_admin_event_path, flash: :error
    end
  end

  def edit
    @report = Event::Report.find params[:id]
  end

  def create
    @report = Event::Report.new params[:event_report]
    if @report.save
      redirect_to admin_event_path(@report.event), flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def update
    @report = Event::Report.find params[:id]
    if @report.update_attributes params[:report]
      redirect_to admin_reports_path, flash: :success
    else
      render action: :edit, flash: :error
    end
  end

  def destroy
    @report = Event::Report.find params[:id]
    @report.destroy
    redirect_to admin_reports_path, flash: :success
  end
end

app/controllers/participant/event/reports_controller.rb
class Participant::Event::ReportsController < Participant::Event::ApplicationController
  def new
    @report = Event::Report.new
    @report.participants.build
  end

  def edit
    @report = Event::Report.find_by_event_id (Event.find_by_user_id params[:id]).id
  end

  def create
    @report = Event::Report.new params[:event_report]
    if @report.save
      redirect_to participant_event_path(@report.event.user), flash: :success
    else
      render action: :new, flash: :error
    end
  end

  def update
    @report = Event::Report.find params[:id]
    if @report.update_attributes params[:event_report]
      redirect_to "/participant/users/#{@report.event.user}/event", flash: :success
    else
      render action: :edit, flash: :error
    end
  end

  def destroy
    @report = Event::Report.find params[:id]
    user = @report.event.user
    @report.destroy
    redirect_to participant_welcome_index_path(user), flash: :success
  end

end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
  def events_without_reports
    Event.all.select { |event| event.report.nil? }
  end
end

app/helpers/participant/event/report_helper.rb
module Participant::Event::ReportHelper
end

app/views/admin/reports/_form.html.haml
= simple_form_for @report, url: { action: action, controller: "admin/reports" }, html: { class: 'form-horizontal' } do |f|
  - f.with_options input_html: { class: :span4 } do |f|
    = f.cktext_area :description
    %br
    = f.label :document
    = f.file_field :document
    = f.input :results
    - if @report.event_id
      = f.input :event_id, as: :hidden, input_html: { value: @report.event.user }
    - else
      = f.association :event, collection: events_without_reports
  .form-actions
    = f.button :submit, class: 'btn-primary'

app/views/admin/reports/edit.html.haml
- model_class = Event::Report
.page-header
  %h1=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize
= render partial: "form", locals: { action: :update }

app/views/admin/reports/index.html.haml
- model_class = Event::Report
.page-header
  %h1=t '.title', default: model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:user)
      %th= model_class.human_attribute_name(:event_id)
      %th= model_class.human_attribute_name(:document)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', default: t("helpers.actions")
  %tbody
    - @reports.each do |report|
      %tr
        %td= link_to report.id, admin_event_path(report.event)
        %td= report.author.full_name
        %td= report.event.title
        %td= link_to t('helpers.general.download'), report.document.url, class: 'btn'
        %td=l report.created_at
        %td
          = link_to t('.edit', default: t("helpers.links.edit")), edit_admin_report_path(report), class: 'btn btn-mini'
          = link_to t('.destroy', default: t("helpers.links.destroy")), admin_report_path(report), method: :delete, data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-mini btn-danger'

= link_to t('.new', default: t("helpers.links.new")), new_admin_report_path, class: 'btn btn-primary'

app/views/admin/reports/new.html.haml
- model_class = Event::Report
.page-header
  %h1=t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize
= render partial: "form", locals: { action: :create }

app/views/admin/reports/show.html.haml
- model_class = Report
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @report.description
%p
  %strong= model_class.human_attribute_name(:document) + ':'
  %br
  = @report.document
%p
  %strong= model_class.human_attribute_name(:event_id) + ':'
  %br
  = @report.event_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), event_reports_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_event_report_path(@report), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), event_report_path(@report), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'